sudo: required
language: scala
jdk: oraclejdk8
scala:
- 2.12.5
services:
- docker
after_success:
- sbt docker:publishLocal
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push USER/REPO
env:
  matrix:
  - secure: S5S3R5zoYNNaMZYN3kb2HZ/K12JdspO1AwQzqyEiDXJeOI89XKDGtzHZZR8208pWkEQJgI3IhIu5EKtbfRI+8V+s+ALCuToOdnMbwlkcMfbWP4FZydMqXxdqdg/svCfbpFs0+YrwTZTSfnuDuX+ZDh8qmx5eM3QcfHZxAfJdzms/BQtpVtlm37tz+bLePYbbnHSozAGYpuPU/1Vr3hA0WTMhA2cPIS9nVTib57QQqBBP+1t2RfouMlhm2w6+Vb7T7T7L7/51+OkIdyvl2OZK6Mgn3e2xWYlJqhV9rE3Y+CLtHPbb/UHfdXIfVAyz2RGp4pRkhlQl5psXPWcxDOPH2X7+xpHekk4UV3LrO1mkNa6pO9A6DL1gCqmcjLGkIPopuyfnJxE88rxk9t4JuzDhIkvDDyRIqJFGO2/LcB7jV+KatVFM6butjCJmwAKxsWbjBhbbhJ1AUhT9lU5c5xrZbJcsmekQTb0rimvEMAbNe5bVhRV149ZpsdginIxpqfeawvRsy/QHkPa7luZbUU/4rfDDjllW+GN0eoiZ5nHBTtPUl+BRWq8mQEORhgspB+EgTKPDDCDc6HXZb74brG7u1obg9gzvyNVbwScjC25pEbP8MX2PPpI0wffTRmKS1mK57IXD55duc0C3TuW6X2SkWOCExRdJG05G0ZAFSRy/VZI=
  - secure: mZz2/snGribrp+RcmMX8khGwY1z1rqrDm8M8AVt/AwHx9jiNRygFBjcNKlt6JeTN01TJgfQPYUeLvjB9gCcq2DjP3fG2ieyUiZPY+QMxqjhveXGt8RAGDPNc9UrpQwvMmKmFcs5q/uoUyMtjETFsVRFhzKFq0YuTX5t4x9YJm34C75fpYfuk/t42ZmRLusI7uRWGU0O7XVeOMNoVKyp2ofWeqcMFovdcfLCRmjOxeSTz/lTbGwwiD7sI5vUTsRR90R058fMdedLkFnOhFaDHJMulX8CTNy9HHr23/ydhPmwXjrsPYhbxHQ+I0GzOQ2zKTNgiZPuADmXw04TRoMS/S4dc1XLHalV31u7HSyNX+lAdHZEzwQ88vFo/i4ePZufaIzd5muirjUpVKlpdkzwSEoonPcZwQKtezrYdCSyh42Ke1RqkeXLFRzSGnG+3VyMLWcXy4Cxxn2mbE/YQqKPTJejGS6yx6OfIWOKuSZzFvCiwcCbfDK/NzXurvFcPngBss9zJ3eYDWL1o49szDzGauRMZSe2OBpXddTAMKK9MhFMZK5tZYUexHTTZWRiLrcQj/7h3lzUtFJyRkFLmnQk7wPHrhfZz3/hlEczb4SeTZ9V2rz/hBPfQ3fUpRynAg+TzbqGC55+AWyNxoI8kXa1MEVUwc8R5BLlrwPGEGL4ormg=
